#!/bin/bash
cd testing
../aggregate.py scarlets-and-blues-classifications.csv -w Alpha-Names | diff -qs GOLDEN_NAMES - && \
diff -qs Index.csv GOLDEN_NameIndex.csv && \
diff -qs Names.csv GOLDEN_Names.csv && \
../aggregate.py scarlets-and-blues-classifications.csv -w Alpha-Index | diff -qs GOLDEN_INDEX - && \
diff -qs Index.csv GOLDEN_INDEX.csv && \
../aggregate.py scarlets-and-blues-classifications2.csv -w Alpha-Minutes | diff -qs GOLDEN_Alpha_Minutes - && \
diff -qs GOLDEN_Alpha-Minutes_Attendees.csv Attendees.csv && \
diff -qs GOLDEN_Alpha-Minutes_Items.csv Items.csv && \
diff -qs GOLDEN_Alpha-Minutes_Comments.csv Comments.csv && \
diff -qs GOLDEN_Alpha-Minutes_Tables.csv Tables.csv && \
../aggregate.py scarlets-and-blues-classifications2.csv -w Alpha-Tables  | diff -qs GOLDEN_Alpha_Tables - && \
diff -qs GOLDEN_Alpha-Tables_Attendees.csv Attendees.csv && \
diff -qs GOLDEN_Alpha-Tables_Items.csv Items.csv && \
diff -qs GOLDEN_Alpha-Tables_Comments.csv Comments.csv && \
diff -qs GOLDEN_Alpha-Tables_Tables.csv Tables.csv && \
../aggregate.py rowtable.csv -w NewTable:Minutes:17077:32.62 | diff -qs GOLDEN_rowtable - && \
diff -qs GOLDEN_rowtable_Attendees.csv Attendees.csv && \
diff -qs GOLDEN_rowtable_Items.csv Items.csv && \
diff -qs GOLDEN_rowtable_Comments.csv Comments.csv && \
diff -qs GOLDEN_rowtable_Tables.csv Tables.csv && \
../aggregate.py scarlets-and-blues-classifications2.csv -w Alpha-Underlining | diff -qs GOLDEN_Lines - && \
diff -qs GOLDEN_Lines.csv Lines.csv && \
! ../aggregate.py test.csv >/dev/null && \
! ../aggregate.py test1.csv >/dev/null && \
! ../aggregate.py test2.csv >/dev/null && \
! ../aggregate.py test3.csv >/dev/null && \
echo -e '\033[0;32mTEST PASSED\033[0m' || \
echo -e '\033[0;31mTEST FAILED\033[0m'
