#!/bin/bash
cd testing
../aggregate.py scarlets-and-blues-classifications.csv -w Index:16899:1.1 | diff -s GOLDEN_NAMES - && \
diff -s Index.csv GOLDEN_NameIndex.csv && \
diff -s Names.csv GOLDEN_Names.csv && \
../aggregate.py scarlets-and-blues-classifications.csv -w Index | diff -s GOLDEN_INDEX - && \
diff -s Index.csv GOLDEN_INDEX.csv && \
! ../aggregate.py test.csv && \
! ../aggregate.py test1.csv && \
! ../aggregate.py test2.csv && \
! ../aggregate.py test3.csv && \
echo -e '\033[0;32mTEST PASSED\033[0m' || \
echo -e '\033[0;31mTEST FAILED\033[0m'
